### ISSUE TITLE
Error During Installation - MacOSX

### ISSUE THREAD

**Issue by DerekCaelin** [openforis/collect-earth#10]
When installing collect-earth-installer-1.12.16-osx, I'm able to progress through most of the installation process. However, I encounter the following message at the stage "Installer.Java.CreateLauncers.Text"

> Problem running post-install step.
> Installation may not complete correctly
> No origin file found that matched /private/var/folders/04/xr73n6ds14I40kccI4n1njr80000gp/T/AppTranslocation/27EF5AD8-9AD3-9AD3-4F6F-9003-512AA4D6F65A/d/CollectEarth-1.12.16-osx-installer.app/collect-earth-installer/src/main/resources/launcher.icons

If I click "OK" at this point, the installation progresses, and I find a desktop link to run Collect Earth, but after displaying a splash screen the program fails to run.

I'm using OS 10.15.7. I obtained the install straight from the Open Foris website.

**Comment by herrtunante** [comment]
Thanks for the warning! We usually test in WIndows or Linux ( have only an old Mac mini for testing which is not super nice to use ;) )

As you say the launcher_icons.icns file seems to be missing and the installer complains, but also, as you say, the installation is able to finnish nevertheless. In my Mac OSX ( also version 10.15.7 ) I end up having a Collect Earth shortcut on the desktop (with a kind of installer icon). Clicking that Collect Earth seems to start well, even though the icon also on the dock shows a java icon rather than Collect Earth´s.

Could you check if there is anything under this folder in your main user folder?
OpenForis/CollectEarth 
If so, try to run Collect Earth directly under it by double clicking the executable CollectEarth-launcher
so something like this : /Users/YOUR_USERNAME/OpenForis/CollectEarth

I will try to fix the icons issue, in the meantime **please let us know if you can run it with this manual procedure**.

Just as a reminder, you will need to have Google Earth Pro installed in your computer independently from Collect Earth
https://www.google.com/earth/download/gep/agree.html?hl=en-GB

**Comment by herrtunante** [comment]
Version **1.13.0** of Collect Earth fixed the installation issue (not finding the launcher_icons.icns file )!
still, the Mac version is behind form the Windows/Linux version as double clicking on a CEP file does not correctly open the project in Collect Earth! You will need to open it through the Collect Earth main menu **File->Import CEP file...**
Sadly, Java desktop functions are not totally available in the newer version of the JRE, we have not been able to fix this issue since 2013!

FINALLY: When you install Collect Earth in OSX as it is not signed you night to right click on the installer and click Open, then you can force the program to run even if it is not signed, more on that here : http://www.openforis.org/support/questions/2531/installing-open-foris-collect-and-collect-earth-in-macos-mojavecatalina

**Comment by DerekCaelin** [comment]
> If so, try to run Collect Earth directly under it by double clicking the executable CollectEarth-launcher
so something like this : /Users/YOUR_USERNAME/OpenForis/CollectEarth
> I will try to fix the icons issue, in the meantime please let us know if you can run it with this manual procedure.

Sorry for the delay in responding. I have tried to run the CollectEarth-launcher executable. It starts to load, shows the Collect Earth splash screen, then abruptly quits - same error as when I try to run the desktop executable. 

Google Earth Pro and the most recent version of Java are installed, and I have told my machine to run the executable despite it being unsigned.
